repos:
  - repo: local
    hooks:
      - id: mdformat
        name: mdFormat
        language: system
        types: [markdown]
        entry: .venv/bin/mdformat --check
        pass_filenames: true
        always_run: false
