name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install-and-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv (pip alternative)
        id: uv
        # Docs: https://github.com/astral-sh/uv?tab=readme-ov-file#getting-started
        run: |
          pip install uv
          # calculate cache parameters
          cache_dependency_path="${{ steps.requirements_path.outputs.requirements_dir_prefix }}requirements.txt"
          ubuntu_version=$(lsb_release -rs)
          restore_key="uv-${{ runner.os }}-Ubuntu-${ubuntu_version}-python-3.12"
          echo "uv_cache_dir=$(uv cache dir)" >> "$GITHUB_OUTPUT"
          echo "cache_dependency_path=${cache_dependency_path}" >> "$GITHUB_OUTPUT"
          echo "cache_restore_key=${restore_key}" >> "$GITHUB_OUTPUT"
        shell: bash

      - name: (Restore) uv cache
        uses:  actions/cache@v4
        with:
          path: ${{ steps.uv.outputs.uv_cache_dir }}
          key: ${{ steps.uv.outputs.cache_restore_key }}-${{ hashFiles(steps.uv.outputs.cache_dependency_path) }}
          restore-keys: |
            ${{ steps.uv.outputs.cache_restore_key }}-
          save-always: 'true'

      - name: Install dependencies
        run: |
          uv pip install \
          --system \
          -r requirements.txt
        shell: bash

      - name: Check markdown formatting
        run: |
          mdformat --check .
        shell: bash
